# Generated by Django 4.2.3 on 2023-07-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origen',
            options={'managed': True, 'verbose_name': 'Origen', 'verbose_name_plural': 'Origen'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterModelTable(
            name='origen',
            table='',
        ),
    ]
