# Generated by Django 4.2.3 on 2023-08-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_origen_options_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='origen',
            field=models.CharField(choices=[('NAC', 'Nacional'), ('IMP', 'Importado')], default=1, max_length=5),
        ),
        migrations.DeleteModel(
            name='Origen',
        ),
    ]
